version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: file-sharing-backend
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_CONNECTION=pg
      - DB_SSL_DISABLED=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: file-sharing-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3333
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: file-sharing-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_magang
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
